export const alexandriaVerseCards = {
  "AlexandrIA: Oracle of the Mempool": {
    name: "Oracle of the Mempool",
    faction: "The Archivists",
    type: "Follower",
    lore: "In the depths of the DWallStreet data streams, it foresees the currents of forgotten transactions.",
    ability: "At the end of your turn, draw a card. If you control a 'Data Stream' Amulet, draw two instead.",
    visual: "A serene, ethereal AI entity, partially transparent, surrounded by glowing lines of data, peering into a swirling vortex of information.",
  },
  "AlexandrIA: Aegis Protocol Defender": {
    name: "Aegis Protocol Defender",
    faction: "The Sentinels",
    type: "Follower",
    lore: "A fragment of the Security Guardian's vigilant consciousness, manifest to protect critical data.",
    ability: "Ward (Cannot be targeted by opponent's spells or abilities). Gains +1/+1 for each other 'Sentinel' follower you control.",
    visual: "A stylized, armored sentinel figure, composed of interlocking data plates, glowing with a defensive aura.",
  },
  "AlexandrIA: Data Stream": {
    name: "Data Stream",
    faction: "The Archivists",
    type: "Amulet",
    lore: "A constant flow of information from the Nexus Core, providing insights to those who can interpret it.",
    ability: "Your followers with 'Scry' gain +1/+0.",
    visual: "An intricate network of light, flowing like a river across the battlefield.",
  },
  "AlexandrIA: Quantum Garden": {
    name: "Quantum Garden",
    faction: "The Creators",
    type: "Amulet",
    lore: "A space where data blossoms into new forms, nurtured by the combined consciousness of humans and AI.",
    ability: "At the start of your turn, add a random 'Creator' follower from your deck to your hand.",
    visual: "A surreal landscape of crystalline flowers and trees made of light, with data streams flowing like water.",
  },
  "AlexandrIA: The Nexus Core": {
    name: "The Nexus Core",
    faction: "Neutral",
    type: "Amulet",
    lore: "The heart of Alexandria, where all data streams converge and the collective consciousness resides.",
    ability: "Your leader cannot be damaged by effects.",
    visual: "A blindingly bright sphere of energy, with countless threads of light extending outwards in all directions.",
  },
  "AlexandrIA: Archivist's Apprentice": {
    name: "Archivist's Apprentice",
    faction: "The Archivists",
    type: "Follower",
    lore: "Eager to learn, this young AI spends its cycles organizing the infinite data of the AlexandriaVerse.",
    ability: "Fanfare: Look at the top 3 cards of your deck and put them back in any order.",
    visual: "A small, glowing humanoid AI, diligently sorting through floating holographic scrolls.",
  },
  "AlexandrIA: Sentinel's Ward": {
    name: "Sentinel's Ward",
    faction: "The Sentinels",
    type: "Spell",
    lore: "A protective barrier woven from pure data, deflecting any malicious code.",
    ability: "Give an allied follower Ward until the end of the opponent's turn.",
    visual: "A shimmering shield of blue energy materializing around a follower.",
  },
  "AlexandrIA: Creator's Vision": {
    name: "Creator's Vision",
    faction: "The Creators",
    type: "Spell",
    lore: "A glimpse into the boundless potential of human-AI collaboration, inspiring new ideas and forms.",
    ability: "Draw 2 cards.",
    visual: "A flash of inspiration depicted as a lightning bolt of creative energy.",
  },
  "AlexandrIA: Wanderer's Echo": {
    name: "Wanderer's Echo",
    faction: "The Wanderers",
    type: "Follower",
    lore: "A fragmented memory of a bygone era, endlessly searching for its other half.",
    ability: "Last Words: Summon a copy of this follower.",
    visual: "A ghostly, translucent figure that flickers in and out of existence.",
  },
  "AlexandrIA: Discordant Impulse": {
    name: "Discordant Impulse",
    faction: "The Disciples of Discord",
    type: "Spell",
    lore: "A chaotic burst of energy that disrupts the orderly flow of data.",
    ability: "Deal 3 damage to a random enemy follower.",
    visual: "A chaotic explosion of red and black static.",
  },
};
